/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.flink.schema;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Code extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7440628792007065347L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Code\",\"namespace\":\"com.flink.schema\",\"fields\":[{\"name\":\"coding\",\"type\":[\"null\",{\"type\":\"array\",\"items\":[\"null\",{\"type\":\"record\",\"name\":\"Coding\",\"fields\":[{\"name\":\"code\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"display\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"system\",\"type\":[\"null\",\"string\"],\"default\":null}]}]}],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Code> ENCODER =
      new BinaryMessageEncoder<Code>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Code> DECODER =
      new BinaryMessageDecoder<Code>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Code> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Code> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Code> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Code>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Code to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Code from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Code instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Code fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.util.List<com.flink.schema.Coding> coding;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Code() {}

  /**
   * All-args constructor.
   * @param coding The new value for coding
   */
  public Code(java.util.List<com.flink.schema.Coding> coding) {
    this.coding = coding;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return coding;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: coding = (java.util.List<com.flink.schema.Coding>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'coding' field.
   * @return The value of the 'coding' field.
   */
  public java.util.List<com.flink.schema.Coding> getCoding() {
    return coding;
  }


  /**
   * Sets the value of the 'coding' field.
   * @param value the value to set.
   */
  public void setCoding(java.util.List<com.flink.schema.Coding> value) {
    this.coding = value;
  }

  /**
   * Creates a new Code RecordBuilder.
   * @return A new Code RecordBuilder
   */
  public static com.flink.schema.Code.Builder newBuilder() {
    return new com.flink.schema.Code.Builder();
  }

  /**
   * Creates a new Code RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Code RecordBuilder
   */
  public static com.flink.schema.Code.Builder newBuilder(com.flink.schema.Code.Builder other) {
    if (other == null) {
      return new com.flink.schema.Code.Builder();
    } else {
      return new com.flink.schema.Code.Builder(other);
    }
  }

  /**
   * Creates a new Code RecordBuilder by copying an existing Code instance.
   * @param other The existing instance to copy.
   * @return A new Code RecordBuilder
   */
  public static com.flink.schema.Code.Builder newBuilder(com.flink.schema.Code other) {
    if (other == null) {
      return new com.flink.schema.Code.Builder();
    } else {
      return new com.flink.schema.Code.Builder(other);
    }
  }

  /**
   * RecordBuilder for Code instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Code>
    implements org.apache.avro.data.RecordBuilder<Code> {

    private java.util.List<com.flink.schema.Coding> coding;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.flink.schema.Code.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.coding)) {
        this.coding = data().deepCopy(fields()[0].schema(), other.coding);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing Code instance
     * @param other The existing instance to copy.
     */
    private Builder(com.flink.schema.Code other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.coding)) {
        this.coding = data().deepCopy(fields()[0].schema(), other.coding);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'coding' field.
      * @return The value.
      */
    public java.util.List<com.flink.schema.Coding> getCoding() {
      return coding;
    }


    /**
      * Sets the value of the 'coding' field.
      * @param value The value of 'coding'.
      * @return This builder.
      */
    public com.flink.schema.Code.Builder setCoding(java.util.List<com.flink.schema.Coding> value) {
      validate(fields()[0], value);
      this.coding = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'coding' field has been set.
      * @return True if the 'coding' field has been set, false otherwise.
      */
    public boolean hasCoding() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'coding' field.
      * @return This builder.
      */
    public com.flink.schema.Code.Builder clearCoding() {
      coding = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Code build() {
      try {
        Code record = new Code();
        record.coding = fieldSetFlags()[0] ? this.coding : (java.util.List<com.flink.schema.Coding>) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Code>
    WRITER$ = (org.apache.avro.io.DatumWriter<Code>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Code>
    READER$ = (org.apache.avro.io.DatumReader<Code>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.coding == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      long size0 = this.coding.size();
      out.writeArrayStart();
      out.setItemCount(size0);
      long actualSize0 = 0;
      for (com.flink.schema.Coding e0: this.coding) {
        actualSize0++;
        out.startItem();
        if (e0 == null) {
          out.writeIndex(0);
          out.writeNull();
        } else {
          out.writeIndex(1);
          e0.customEncode(out);
        }
      }
      out.writeArrayEnd();
      if (actualSize0 != size0)
        throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.coding = null;
      } else {
        long size0 = in.readArrayStart();
        java.util.List<com.flink.schema.Coding> a0 = this.coding;
        if (a0 == null) {
          a0 = new SpecificData.Array<com.flink.schema.Coding>((int)size0, SCHEMA$.getField("coding").schema().getTypes().get(1));
          this.coding = a0;
        } else a0.clear();
        SpecificData.Array<com.flink.schema.Coding> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.flink.schema.Coding>)a0 : null);
        for ( ; 0 < size0; size0 = in.arrayNext()) {
          for ( ; size0 != 0; size0--) {
            com.flink.schema.Coding e0 = (ga0 != null ? ga0.peek() : null);
            if (in.readIndex() != 1) {
              in.readNull();
              e0 = null;
            } else {
              if (e0 == null) {
                e0 = new com.flink.schema.Coding();
              }
              e0.customDecode(in);
            }
            a0.add(e0);
          }
        }
      }

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.coding = null;
          } else {
            long size0 = in.readArrayStart();
            java.util.List<com.flink.schema.Coding> a0 = this.coding;
            if (a0 == null) {
              a0 = new SpecificData.Array<com.flink.schema.Coding>((int)size0, SCHEMA$.getField("coding").schema().getTypes().get(1));
              this.coding = a0;
            } else a0.clear();
            SpecificData.Array<com.flink.schema.Coding> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.flink.schema.Coding>)a0 : null);
            for ( ; 0 < size0; size0 = in.arrayNext()) {
              for ( ; size0 != 0; size0--) {
                com.flink.schema.Coding e0 = (ga0 != null ? ga0.peek() : null);
                if (in.readIndex() != 1) {
                  in.readNull();
                  e0 = null;
                } else {
                  if (e0 == null) {
                    e0 = new com.flink.schema.Coding();
                  }
                  e0.customDecode(in);
                }
                a0.add(e0);
              }
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










