/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.flink.schema;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class EffectivePeriod extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4176224528050691609L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"EffectivePeriod\",\"namespace\":\"com.flink.schema\",\"fields\":[{\"name\":\"end\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"start\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<EffectivePeriod> ENCODER =
      new BinaryMessageEncoder<EffectivePeriod>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<EffectivePeriod> DECODER =
      new BinaryMessageDecoder<EffectivePeriod>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<EffectivePeriod> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<EffectivePeriod> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<EffectivePeriod> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<EffectivePeriod>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this EffectivePeriod to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a EffectivePeriod from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a EffectivePeriod instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static EffectivePeriod fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence end;
  @Deprecated public java.lang.CharSequence start;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public EffectivePeriod() {}

  /**
   * All-args constructor.
   * @param end The new value for end
   * @param start The new value for start
   */
  public EffectivePeriod(java.lang.CharSequence end, java.lang.CharSequence start) {
    this.end = end;
    this.start = start;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return end;
    case 1: return start;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: end = (java.lang.CharSequence)value$; break;
    case 1: start = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'end' field.
   * @return The value of the 'end' field.
   */
  public java.lang.CharSequence getEnd() {
    return end;
  }


  /**
   * Sets the value of the 'end' field.
   * @param value the value to set.
   */
  public void setEnd(java.lang.CharSequence value) {
    this.end = value;
  }

  /**
   * Gets the value of the 'start' field.
   * @return The value of the 'start' field.
   */
  public java.lang.CharSequence getStart() {
    return start;
  }


  /**
   * Sets the value of the 'start' field.
   * @param value the value to set.
   */
  public void setStart(java.lang.CharSequence value) {
    this.start = value;
  }

  /**
   * Creates a new EffectivePeriod RecordBuilder.
   * @return A new EffectivePeriod RecordBuilder
   */
  public static com.flink.schema.EffectivePeriod.Builder newBuilder() {
    return new com.flink.schema.EffectivePeriod.Builder();
  }

  /**
   * Creates a new EffectivePeriod RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new EffectivePeriod RecordBuilder
   */
  public static com.flink.schema.EffectivePeriod.Builder newBuilder(com.flink.schema.EffectivePeriod.Builder other) {
    if (other == null) {
      return new com.flink.schema.EffectivePeriod.Builder();
    } else {
      return new com.flink.schema.EffectivePeriod.Builder(other);
    }
  }

  /**
   * Creates a new EffectivePeriod RecordBuilder by copying an existing EffectivePeriod instance.
   * @param other The existing instance to copy.
   * @return A new EffectivePeriod RecordBuilder
   */
  public static com.flink.schema.EffectivePeriod.Builder newBuilder(com.flink.schema.EffectivePeriod other) {
    if (other == null) {
      return new com.flink.schema.EffectivePeriod.Builder();
    } else {
      return new com.flink.schema.EffectivePeriod.Builder(other);
    }
  }

  /**
   * RecordBuilder for EffectivePeriod instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<EffectivePeriod>
    implements org.apache.avro.data.RecordBuilder<EffectivePeriod> {

    private java.lang.CharSequence end;
    private java.lang.CharSequence start;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.flink.schema.EffectivePeriod.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.end)) {
        this.end = data().deepCopy(fields()[0].schema(), other.end);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.start)) {
        this.start = data().deepCopy(fields()[1].schema(), other.start);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing EffectivePeriod instance
     * @param other The existing instance to copy.
     */
    private Builder(com.flink.schema.EffectivePeriod other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.end)) {
        this.end = data().deepCopy(fields()[0].schema(), other.end);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.start)) {
        this.start = data().deepCopy(fields()[1].schema(), other.start);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'end' field.
      * @return The value.
      */
    public java.lang.CharSequence getEnd() {
      return end;
    }


    /**
      * Sets the value of the 'end' field.
      * @param value The value of 'end'.
      * @return This builder.
      */
    public com.flink.schema.EffectivePeriod.Builder setEnd(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.end = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'end' field has been set.
      * @return True if the 'end' field has been set, false otherwise.
      */
    public boolean hasEnd() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'end' field.
      * @return This builder.
      */
    public com.flink.schema.EffectivePeriod.Builder clearEnd() {
      end = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'start' field.
      * @return The value.
      */
    public java.lang.CharSequence getStart() {
      return start;
    }


    /**
      * Sets the value of the 'start' field.
      * @param value The value of 'start'.
      * @return This builder.
      */
    public com.flink.schema.EffectivePeriod.Builder setStart(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.start = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'start' field has been set.
      * @return True if the 'start' field has been set, false otherwise.
      */
    public boolean hasStart() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'start' field.
      * @return This builder.
      */
    public com.flink.schema.EffectivePeriod.Builder clearStart() {
      start = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public EffectivePeriod build() {
      try {
        EffectivePeriod record = new EffectivePeriod();
        record.end = fieldSetFlags()[0] ? this.end : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.start = fieldSetFlags()[1] ? this.start : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<EffectivePeriod>
    WRITER$ = (org.apache.avro.io.DatumWriter<EffectivePeriod>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<EffectivePeriod>
    READER$ = (org.apache.avro.io.DatumReader<EffectivePeriod>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.end == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.end);
    }

    if (this.start == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.start);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.end = null;
      } else {
        this.end = in.readString(this.end instanceof Utf8 ? (Utf8)this.end : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.start = null;
      } else {
        this.start = in.readString(this.start instanceof Utf8 ? (Utf8)this.start : null);
      }

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.end = null;
          } else {
            this.end = in.readString(this.end instanceof Utf8 ? (Utf8)this.end : null);
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.start = null;
          } else {
            this.start = in.readString(this.start instanceof Utf8 ? (Utf8)this.start : null);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










