/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.flink.schema;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Identifier extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -746283064141765203L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Identifier\",\"namespace\":\"com.flink.schema\",\"fields\":[{\"name\":\"system\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"use\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"value\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Identifier> ENCODER =
      new BinaryMessageEncoder<Identifier>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Identifier> DECODER =
      new BinaryMessageDecoder<Identifier>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Identifier> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Identifier> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Identifier> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Identifier>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Identifier to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Identifier from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Identifier instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Identifier fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence system;
  @Deprecated public java.lang.CharSequence use;
  @Deprecated public java.lang.CharSequence value;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Identifier() {}

  /**
   * All-args constructor.
   * @param system The new value for system
   * @param use The new value for use
   * @param value The new value for value
   */
  public Identifier(java.lang.CharSequence system, java.lang.CharSequence use, java.lang.CharSequence value) {
    this.system = system;
    this.use = use;
    this.value = value;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return system;
    case 1: return use;
    case 2: return value;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: system = (java.lang.CharSequence)value$; break;
    case 1: use = (java.lang.CharSequence)value$; break;
    case 2: value = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'system' field.
   * @return The value of the 'system' field.
   */
  public java.lang.CharSequence getSystem() {
    return system;
  }


  /**
   * Sets the value of the 'system' field.
   * @param value the value to set.
   */
  public void setSystem(java.lang.CharSequence value) {
    this.system = value;
  }

  /**
   * Gets the value of the 'use' field.
   * @return The value of the 'use' field.
   */
  public java.lang.CharSequence getUse() {
    return use;
  }


  /**
   * Sets the value of the 'use' field.
   * @param value the value to set.
   */
  public void setUse(java.lang.CharSequence value) {
    this.use = value;
  }

  /**
   * Gets the value of the 'value' field.
   * @return The value of the 'value' field.
   */
  public java.lang.CharSequence getValue() {
    return value;
  }


  /**
   * Sets the value of the 'value' field.
   * @param value the value to set.
   */
  public void setValue(java.lang.CharSequence value) {
    this.value = value;
  }

  /**
   * Creates a new Identifier RecordBuilder.
   * @return A new Identifier RecordBuilder
   */
  public static com.flink.schema.Identifier.Builder newBuilder() {
    return new com.flink.schema.Identifier.Builder();
  }

  /**
   * Creates a new Identifier RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Identifier RecordBuilder
   */
  public static com.flink.schema.Identifier.Builder newBuilder(com.flink.schema.Identifier.Builder other) {
    if (other == null) {
      return new com.flink.schema.Identifier.Builder();
    } else {
      return new com.flink.schema.Identifier.Builder(other);
    }
  }

  /**
   * Creates a new Identifier RecordBuilder by copying an existing Identifier instance.
   * @param other The existing instance to copy.
   * @return A new Identifier RecordBuilder
   */
  public static com.flink.schema.Identifier.Builder newBuilder(com.flink.schema.Identifier other) {
    if (other == null) {
      return new com.flink.schema.Identifier.Builder();
    } else {
      return new com.flink.schema.Identifier.Builder(other);
    }
  }

  /**
   * RecordBuilder for Identifier instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Identifier>
    implements org.apache.avro.data.RecordBuilder<Identifier> {

    private java.lang.CharSequence system;
    private java.lang.CharSequence use;
    private java.lang.CharSequence value;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.flink.schema.Identifier.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.system)) {
        this.system = data().deepCopy(fields()[0].schema(), other.system);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.use)) {
        this.use = data().deepCopy(fields()[1].schema(), other.use);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.value)) {
        this.value = data().deepCopy(fields()[2].schema(), other.value);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing Identifier instance
     * @param other The existing instance to copy.
     */
    private Builder(com.flink.schema.Identifier other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.system)) {
        this.system = data().deepCopy(fields()[0].schema(), other.system);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.use)) {
        this.use = data().deepCopy(fields()[1].schema(), other.use);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.value)) {
        this.value = data().deepCopy(fields()[2].schema(), other.value);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'system' field.
      * @return The value.
      */
    public java.lang.CharSequence getSystem() {
      return system;
    }


    /**
      * Sets the value of the 'system' field.
      * @param value The value of 'system'.
      * @return This builder.
      */
    public com.flink.schema.Identifier.Builder setSystem(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.system = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'system' field has been set.
      * @return True if the 'system' field has been set, false otherwise.
      */
    public boolean hasSystem() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'system' field.
      * @return This builder.
      */
    public com.flink.schema.Identifier.Builder clearSystem() {
      system = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'use' field.
      * @return The value.
      */
    public java.lang.CharSequence getUse() {
      return use;
    }


    /**
      * Sets the value of the 'use' field.
      * @param value The value of 'use'.
      * @return This builder.
      */
    public com.flink.schema.Identifier.Builder setUse(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.use = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'use' field has been set.
      * @return True if the 'use' field has been set, false otherwise.
      */
    public boolean hasUse() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'use' field.
      * @return This builder.
      */
    public com.flink.schema.Identifier.Builder clearUse() {
      use = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'value' field.
      * @return The value.
      */
    public java.lang.CharSequence getValue() {
      return value;
    }


    /**
      * Sets the value of the 'value' field.
      * @param value The value of 'value'.
      * @return This builder.
      */
    public com.flink.schema.Identifier.Builder setValue(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.value = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'value' field has been set.
      * @return True if the 'value' field has been set, false otherwise.
      */
    public boolean hasValue() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'value' field.
      * @return This builder.
      */
    public com.flink.schema.Identifier.Builder clearValue() {
      value = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Identifier build() {
      try {
        Identifier record = new Identifier();
        record.system = fieldSetFlags()[0] ? this.system : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.use = fieldSetFlags()[1] ? this.use : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.value = fieldSetFlags()[2] ? this.value : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Identifier>
    WRITER$ = (org.apache.avro.io.DatumWriter<Identifier>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Identifier>
    READER$ = (org.apache.avro.io.DatumReader<Identifier>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.system == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.system);
    }

    if (this.use == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.use);
    }

    if (this.value == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.value);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.system = null;
      } else {
        this.system = in.readString(this.system instanceof Utf8 ? (Utf8)this.system : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.use = null;
      } else {
        this.use = in.readString(this.use instanceof Utf8 ? (Utf8)this.use : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.value = null;
      } else {
        this.value = in.readString(this.value instanceof Utf8 ? (Utf8)this.value : null);
      }

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.system = null;
          } else {
            this.system = in.readString(this.system instanceof Utf8 ? (Utf8)this.system : null);
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.use = null;
          } else {
            this.use = in.readString(this.use instanceof Utf8 ? (Utf8)this.use : null);
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.value = null;
          } else {
            this.value = in.readString(this.value instanceof Utf8 ? (Utf8)this.value : null);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










