/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.flink.schema;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Subject extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6542728075732506966L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Subject\",\"namespace\":\"com.flink.schema\",\"fields\":[{\"name\":\"display\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"reference\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Subject> ENCODER =
      new BinaryMessageEncoder<Subject>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Subject> DECODER =
      new BinaryMessageDecoder<Subject>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Subject> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Subject> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Subject> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Subject>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Subject to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Subject from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Subject instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Subject fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence display;
  @Deprecated public java.lang.CharSequence reference;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Subject() {}

  /**
   * All-args constructor.
   * @param display The new value for display
   * @param reference The new value for reference
   */
  public Subject(java.lang.CharSequence display, java.lang.CharSequence reference) {
    this.display = display;
    this.reference = reference;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return display;
    case 1: return reference;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: display = (java.lang.CharSequence)value$; break;
    case 1: reference = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'display' field.
   * @return The value of the 'display' field.
   */
  public java.lang.CharSequence getDisplay() {
    return display;
  }


  /**
   * Sets the value of the 'display' field.
   * @param value the value to set.
   */
  public void setDisplay(java.lang.CharSequence value) {
    this.display = value;
  }

  /**
   * Gets the value of the 'reference' field.
   * @return The value of the 'reference' field.
   */
  public java.lang.CharSequence getReference() {
    return reference;
  }


  /**
   * Sets the value of the 'reference' field.
   * @param value the value to set.
   */
  public void setReference(java.lang.CharSequence value) {
    this.reference = value;
  }

  /**
   * Creates a new Subject RecordBuilder.
   * @return A new Subject RecordBuilder
   */
  public static com.flink.schema.Subject.Builder newBuilder() {
    return new com.flink.schema.Subject.Builder();
  }

  /**
   * Creates a new Subject RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Subject RecordBuilder
   */
  public static com.flink.schema.Subject.Builder newBuilder(com.flink.schema.Subject.Builder other) {
    if (other == null) {
      return new com.flink.schema.Subject.Builder();
    } else {
      return new com.flink.schema.Subject.Builder(other);
    }
  }

  /**
   * Creates a new Subject RecordBuilder by copying an existing Subject instance.
   * @param other The existing instance to copy.
   * @return A new Subject RecordBuilder
   */
  public static com.flink.schema.Subject.Builder newBuilder(com.flink.schema.Subject other) {
    if (other == null) {
      return new com.flink.schema.Subject.Builder();
    } else {
      return new com.flink.schema.Subject.Builder(other);
    }
  }

  /**
   * RecordBuilder for Subject instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Subject>
    implements org.apache.avro.data.RecordBuilder<Subject> {

    private java.lang.CharSequence display;
    private java.lang.CharSequence reference;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.flink.schema.Subject.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.display)) {
        this.display = data().deepCopy(fields()[0].schema(), other.display);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.reference)) {
        this.reference = data().deepCopy(fields()[1].schema(), other.reference);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing Subject instance
     * @param other The existing instance to copy.
     */
    private Builder(com.flink.schema.Subject other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.display)) {
        this.display = data().deepCopy(fields()[0].schema(), other.display);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.reference)) {
        this.reference = data().deepCopy(fields()[1].schema(), other.reference);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'display' field.
      * @return The value.
      */
    public java.lang.CharSequence getDisplay() {
      return display;
    }


    /**
      * Sets the value of the 'display' field.
      * @param value The value of 'display'.
      * @return This builder.
      */
    public com.flink.schema.Subject.Builder setDisplay(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.display = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'display' field has been set.
      * @return True if the 'display' field has been set, false otherwise.
      */
    public boolean hasDisplay() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'display' field.
      * @return This builder.
      */
    public com.flink.schema.Subject.Builder clearDisplay() {
      display = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'reference' field.
      * @return The value.
      */
    public java.lang.CharSequence getReference() {
      return reference;
    }


    /**
      * Sets the value of the 'reference' field.
      * @param value The value of 'reference'.
      * @return This builder.
      */
    public com.flink.schema.Subject.Builder setReference(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.reference = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'reference' field has been set.
      * @return True if the 'reference' field has been set, false otherwise.
      */
    public boolean hasReference() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'reference' field.
      * @return This builder.
      */
    public com.flink.schema.Subject.Builder clearReference() {
      reference = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Subject build() {
      try {
        Subject record = new Subject();
        record.display = fieldSetFlags()[0] ? this.display : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.reference = fieldSetFlags()[1] ? this.reference : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Subject>
    WRITER$ = (org.apache.avro.io.DatumWriter<Subject>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Subject>
    READER$ = (org.apache.avro.io.DatumReader<Subject>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.display == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.display);
    }

    if (this.reference == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.reference);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.display = null;
      } else {
        this.display = in.readString(this.display instanceof Utf8 ? (Utf8)this.display : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.reference = null;
      } else {
        this.reference = in.readString(this.reference instanceof Utf8 ? (Utf8)this.reference : null);
      }

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.display = null;
          } else {
            this.display = in.readString(this.display instanceof Utf8 ? (Utf8)this.display : null);
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.reference = null;
          } else {
            this.reference = in.readString(this.reference instanceof Utf8 ? (Utf8)this.reference : null);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










